version: "3"
services:
    sharepostapp:
        build: .
        depends_on: 
            - mariadb
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html/sharepostapp
        links: 
            - mariadb:mariadb
    mariadb:
        image: mariadb
        volumes: 
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql  
        restart: always
        ports: 
            - "13306:3306"
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
